Automatic Wifi STA connection at boot
mmbnetworks/esp-idf pull request #1
Opened 2023-07-28 19:23 UTC by rretanubun

# Why this change
- To make it simpler for DUT testing, we make the wifi STA client auto-connect to a known ssid and password (`testSSID` / `testPassword`)
- To make it simpler to get the status of the DUT, we extend the `query` command to show the `ssid, mac-address, and ip-address`
- To give quidance we updated the help message of the example app

# Envisioned use case
- Setup Wifi Router with `testSSID` and `testPassword`
- Boot the DUT and run `query` once connection is established, like this:
```
 ========================================================
 |       Steps to use this test program                   |
 |                                                        |
 |  1. Setup a Wifi Router with testSSID/testPassword     |
 |  2. Setup the DHCP server on router to assign          |
 |     a static IP for this device's Mac Address          |
 |                                                        |
 |  3. Device will auto connect to a known SSID:          |
 |     testSSID/testPassword as a Wifi Client             |
 |  4. Device will also advertise as ESP-BLE-MESH on BT   |
 |                                                        |
 |  5. Print 'help' to gain overview of commands          |
 =================================================

Auto joining Wifi At: testSSID / testPassword
esp> I (4722) iperf: L2 connected
W (4729) wifi:<ba-add>idx:0 (ifx:0, 9c:53:22:61:b6:bb), tid:0, ssn:0, winSize:64
I (5376) esp_netif_handlers: sta ip: 192.168.8.116, mask: 255.255.255.0, gw: 192.168.8.1
I (5378) iperf: got ip

[OK] (will retry if disconnected)
esp>

esp> query
I (11767) iperf: sta mode, connected
I (11768) iperf: ssid: testSSID
I (11768) iperf: mac : 10:97:bd:31:9c:10
I (11779) iperf: ip  : 192.168.8.116
```

- On the `router's GUI` setup a `static IPv4 map` on DHCPv4 server. Using `D-Link DIR-605L` as an example
- [DIR-605LManual_v1.00.pdf](https://github.com/mmbnetworks/esp-idf/files/12197665/DIR-605LManual_v1.00.pdf)
![image](https://github.com/mmbnetworks/esp-idf/assets/65364552/dafde53a-8df8-4643-933b-89d696c4d4c2)

- Then on a PC that is connected on the same network, we can initiate `ping -i 1 <ipv4-address>` to send pings once per second
- At the same time, on an Android Phone we can observe that `ESP-BLE-MESH` is being advertised

# Dev Testing
- I was able to Ping over Wifi connected BRD21 and observe the bluetooth device advertised on Android phone (Pixel 3 with Android 12 OS)

2023-07-31 13:00 UTC, mmb-davidsmith requested changes
From what I can tell we're not planning on merging the `BAVFW-1560-Wifi-BLE-CoExist` branch into the main codebase. I wouldn't want this fork to diverge from the main repo if at all possible.

2023-07-31 13:00 UTC, mmb-davidsmith commented on examples/bluetooth/esp_ble_mesh/ble_mesh_wifi_coexist/main/main.c
> +    printf(" |     testSSID/testPassword as a Wifi Client             |\n");
I would suggest that this (and lines 827/828 below) be set up to pull from some config variables.

2023-07-31 13:08 UTC, hani-n approved these changes

2023-07-31 18:53 UTC, hani-n requested changes

2023-07-31 18:53 UTC, hani-n commented on examples/bluetooth/esp_ble_mesh/ble_mesh_wifi_coexist/main/cmd_decl.h
> +
I think you need to `include stdbool.h` here, otehrwise we get compiler errors

2023-08-01 16:42 UTC, hani-n approved these changes

2023-08-01 16:44 UTC, rretanubun commented on examples/bluetooth/esp_ble_mesh/ble_mesh_wifi_coexist/main/main.c
> +    printf(" |     testSSID/testPassword as a Wifi Client             |\n");
good point, now driven by `sdkconfig` options:
- `CONFIG_MMB_WIFI_STA_AUTO_JOIN_SSID`
- `CONFIG_MMB_WIFI_STA_AUTO_JOIN_PASSWORD`

2023-08-01 16:44 UTC, rretanubun commented on examples/bluetooth/esp_ble_mesh/ble_mesh_wifi_coexist/main/cmd_decl.h
> +
nice catch, thanks!

2023-08-01 16:56 UTC, rretanubun commented on examples/bluetooth/esp_ble_mesh/ble_mesh_wifi_coexist/main/main.c
> +    printf(" |     testSSID/testPassword as a Wifi Client             |\n");
the idea of the `fork` is that `main` branch continues to track `esp-idf` proper and the `BAVFW-1560-Wifi-BLE-CoExist` is a `working snapshot` based on `v5.0.1` with just these changes. Since we use this for lab testing (which is a very limited use case) typically we do not need security fixes and whatnot since we only use very limited functions of the device.

I intentionally use existing API / example code as much as possible and try to limit the number of files we touched.

2023-08-04 15:47 UTC, rretanubun commented
As mentioned by @TanvirKaz in BAVFW-1560, the state of this branch is working for him and can be merged. I am doing this now. Further follow up on power level adjustments can be worked on its own ticket.

![image](https://github.com/mmbnetworks/esp-idf/assets/65364552/4e0e8168-1d84-470c-86cd-a97418a5a6a4)

2023-08-04 15:47 UTC, merged